name: GitHub Pages Deployment

on:
  push:
    branches: [main]

jobs:
  project-setup:
    uses: devilsec/website/.github/workflows/setup-project.yml@main
    with:
        main-branch: true
        production: true
        build: true
  deploy:
    runs-on: ubuntu-latest
    needs: project-setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Retrieve Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.project-setup.outputs.export-dir }}
      - name: Extract Tarball
        run: |
          tar -xvf ${{ needs.project-setup.outputs.export-dir }}.tar
          rm ./${{ needs.project-setup.outputs.export-dir }}.tar
      - name: Deploy on GH Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist
