name: GitHub Pages Deployment

on:
  push:
    branches: [main]

jobs:
  project-setup:
    uses: devilsec/website/.github/workflows/setup-project.yml@main
    with:
        main-branch: true
        production: true
        build: true
  deploy:
    runs-on: ubuntu-latest
    needs: setup-project
    steps:
      - name: Checkout # Checkout simply to fix issues with GH deploy
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Retrieve Build
        uses: actions/download-artifact@v1
        with:
          name: website-gh-actions-build
      - name: Deploy on GH Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: website-gh-actions-build
