name: Lint Report

on:
  workflow_dispatch:
    inputs:
      js:
        description: 'Whether JS code should be included.'
        default: true
        required: false
        type: boolean
      css:
        description: 'Whether CSS and SCSS should be included.'
        default: true
        required: false
        type: boolean
  workflow_call:
    inputs:
      js:
        description: 'Whether JS code should be included.'
        default: true
        required: false
        type: boolean
      css:
        description: 'Whether CSS and SCSS should be included.'
        default: true
        required: false
        type: boolean
  pull_request:
    branches: [main]

jobs:
  project-setup:
    uses: devilsec/website/.github/workflows/setup-project.yml@main
  js-lint:
    if: ${{ inputs.js == true }} || ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: project-setup
    steps:
      - name: Retrieve Source Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.project-setup.outputs.export-dir }}
      - name: Extract Tarball
        run: |
          tar -xvf ${{ needs.project-setup.outputs.export-dir }}.tar
          rm ./${{ needs.project-setup.outputs.export-dir }}.tar
      - name: Lint JS Files
        uses: Maggi64/eslint-plus-action@master
        with:
          issueSummary: true
          issueSummaryType: full
          issueSummaryMethod: refresh
          reportIgnoredFiles: true
  css-lint:
    if: ${{ inputs.css == true }} || ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: project-setup
    steps:
      - name: Retrieve Source Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.project-setup.outputs.export-dir }}
      - name: Extract Tarball
        run: |
          tar -xvf ${{ needs.project-setup.outputs.export-dir }}.tar
          rm ./${{ needs.project-setup.outputs.export-dir }}.tar
      - name: Lint CSS Files
        uses: actions-hub/stylelint@master
        env:
          INDENT_SPACES: 2
          PATTERN: "**/*.{css,scss}"
