name: Lint Report

on:
  - workflow_call
  - workflow_dispatch

jobs:
  project-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: ./github/workflows/setup-project
  js-lint:
    runs-on: ubuntu-latest
    needs: project-setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Retrieve pre-setup project
        uses: actions/download-artifact@v1
        with:
          name: ${{ needs.project-setup.outputs.BUILD_NAME }}
      - name: Lint JS Files
        uses: Maggi64/eslint-plus-action@master
        with:
          issueSummary: true
          issueSummaryType: full
          issueSummaryMethod: refresh
          reportIgnoredFiles: true
  css-lint:
    runs-on: ubuntu-latest
    needs: project-setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Retrieve pre-setup project
        uses: actions/download-artifact@v1
        with:
          name: ${{ needs.project-setup.outputs.BUILD_NAME }}
      - name: Lint CSS Files
        uses: actions-hub/stylelint@master
        env:
          INDENT_SPACES: 2
          PATTERN: "**/*.{css,scss}"
