name: Setup Project and Node Environment

on:
  workflow_call:
    inputs:
      main-branch:
        description: 'Whether to utilise the main branch or the current branch'
        default: false
        required: false
        type: boolean
      production:
        description: 'Whether this is a production environment or not'
        default: false
        required: false
        type: boolean
      build:
        description: 'Whether the project is to be built or not'
        default: false
        required: false
        type: boolean
    outputs:
      export-dir:
        value: ${{ jobs.setup-project.outputs.export-dir }}

jobs:
  setup-project:
    runs-on: ubuntu-latest
    outputs:
      export-dir: ${{ steps.output-dir.outputs.export-dir }}
    steps:
      - name: Checkout Main Branch
        if: ${{ inputs.main-branch == true }}
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false
          submodules: recursive
      - name: Checkout Branch
        if: ${{ inputs.main-branch != true }}
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set Production Environment Variable
        if: ${{ inputs.production == true }}
        run: echo "NODE_ENV=production" >> $GITHUB_ENV
      - name: Install Node Packages
        run: npm install
      - name: Build Project
        if: ${{ inputs.build == true }}
        run: npm run build
      - name: Set Build Name
        run: echo "BUILD_NAME=$(($(date +%s)*$RANDOM^2))" >> $GITHUB_ENV
      - name: Export Build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_NAME }}
          path: ./
          retention-days: 1
      - name: Output Directory Name
        id: output-dir
        run: echo '::set-output name=export-dir::${{ env.BUILD_NAME }}'
