name: Validate HTML

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  project-setup:
    uses: devilsec/website/.github/workflows/setup-project.yml@main
  val-html:
    runs-on: ubuntu-latest
    needs: project-setup
    steps:
      - name: Retrieve Source Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.project-setup.outputs.export-dir }}
      - name: Extract Tarball
        run: |
          tar -xvf ${{ needs.project-setup.outputs.export-dir }}.tar
          rm ./${{ needs.project-setup.outputs.export-dir }}.tar
      - name: Validate HTML
        run: |
          npm run val-html
